# Generated by Django 6.0.4 on 2026-04-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblFile',
            fields=[
                ('file_id', models.AutoField(db_column='FILE_ID', primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='FILE_NAME', max_length=100)),
                ('file_ext', models.CharField(db_column='FILE_EXT', max_length=10)),
                ('file_path', models.CharField(db_column='FILE_PATH', max_length=300)),
                ('insurance_name', models.CharField(db_column='INSURANCE_NAME', max_length=100)),
            ],
            options={
                'db_table': 'tbl_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('user_id', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('user_nk', models.CharField(db_column='USER_NK', max_length=50)),
                ('user_email', models.CharField(db_column='USER_EMAIL', max_length=100, unique=True)),
                ('user_pw', models.CharField(db_column='USER_PW', max_length=255)),
                ('pw_wrong_cnt', models.IntegerField(db_column='PW_WRONG_CNT', default=0)),
                ('is_temp_pw', models.CharField(db_column='IS_TEMP_PW', default='N', max_length=1)),
                ('updt_dt', models.DateTimeField(blank=True, db_column='UPDT_DT', null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('last_login_dt', models.DateTimeField(blank=True, db_column='LAST_LOGIN_DT', null=True)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblVerifyCode',
            fields=[
                ('verify_code_id', models.AutoField(db_column='VERIFY_CODE_ID', primary_key=True, serialize=False)),
                ('user_email', models.CharField(db_column='USER_EMAIL', max_length=50)),
                ('verify_code', models.CharField(db_column='VERIFY_CODE', max_length=50)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('req_ip', models.CharField(db_column='REQ_IP', max_length=50)),
            ],
            options={
                'db_table': 'tbl_verify_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblFeedback',
            fields=[
                ('feedback_id', models.AutoField(db_column='FEEDBACK_ID', primary_key=True, serialize=False)),
                ('satisfaction_level', models.IntegerField(db_column='SATISFACTION_LEVEL')),
                ('feedback_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dacare.tbluser')),
            ],
            options={
                'db_table': 'tbl_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserChatHistory',
            fields=[
                ('chat_id', models.AutoField(db_column='CHAT_ID', primary_key=True, serialize=False)),
                ('chat_title', models.CharField(db_column='CHAT_TITLE', max_length=50)),
                ('session_id', models.CharField(db_column='SESSION_ID', max_length=100)),
                ('insurance_name', models.CharField(db_column='INSURANCE_NAME', max_length=100)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='dacare.tbluser')),
            ],
            options={
                'db_table': 'tbl_user_chat_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserChatHistDtl',
            fields=[
                ('chat_dtl_id', models.AutoField(db_column='CHAT_DTL_ID', primary_key=True, serialize=False)),
                ('bot_yn', models.CharField(db_column='BOT_YN', max_length=1)),
                ('chat_content', models.CharField(db_column='CHAT_CONTENT', max_length=1500)),
                ('chat_content_all', models.JSONField(blank=True, db_column='CHAT_CONTENT_ALL', null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('chat', models.ForeignKey(db_column='CHAT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dacare.tbluserchathistory')),
            ],
            options={
                'db_table': 'tbl_user_chat_hist_dtl',
                'managed': True,
            },
        ),
    ]
