# Generated by Django 6.0.4 on 2026-04-22 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblFile',
            fields=[
                ('FILE_ID', models.AutoField(db_column='FILE_ID', primary_key=True, serialize=False)),
                ('FILE_NAME', models.CharField(db_column='FILE_NAME', max_length=100)),
                ('FILE_EXT', models.CharField(db_column='FILE_EXT', default='pdf', max_length=10)),
                ('FILE_PATH', models.CharField(db_column='FILE_PATH', max_length=300)),
                ('INSURANCE_NAME', models.CharField(db_column='INSURANCE_NAME', max_length=100)),
            ],
            options={
                'db_table': 'TBL_FILE',
                'indexes': [models.Index(fields=['INSURANCE_NAME'], name='IDX_TBL_FILE_INSURANCE_NAME')],
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('USER_ID', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('USER_NK', models.CharField(db_column='USER_NK', max_length=50)),
                ('USER_EMAIL', models.CharField(db_column='USER_EMAIL', max_length=100, unique=True)),
                ('USER_PW', models.CharField(db_column='USER_PW', max_length=100)),
                ('PW_WRONG_CNT', models.IntegerField(db_column='PW_WRONG_CNT', default=0)),
                ('IS_TEMP_PW', models.CharField(db_column='IS_TEMP_PW', default='N', max_length=1)),
                ('UPDT_DT', models.DateTimeField(db_column='UPDT_DT')),
                ('REG_DT', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('LAST_LOGIN_DT', models.DateTimeField(auto_now_add=True, db_column='LAST_LOGIN_DT')),
            ],
            options={
                'db_table': 'TBL_USER',
                'constraints': [models.CheckConstraint(condition=models.Q(('IS_TEMP_PW__in', ['Y', 'N'])), name='CK_TBL_USER_IS_TEMP_PW')],
            },
        ),
        migrations.CreateModel(
            name='TblUserChatHistory',
            fields=[
                ('CHAT_ID', models.AutoField(db_column='CHAT_ID', primary_key=True, serialize=False)),
                ('CHAT_TITLE', models.CharField(db_column='CHAT_TITLE', max_length=50)),
                ('SESSION_ID', models.CharField(db_column='SESSION_ID', max_length=100)),
                ('REG_DT', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='dacare.tbluser')),
            ],
            options={
                'db_table': 'TBL_USER_CHAT_HISTORY',
            },
        ),
        migrations.CreateModel(
            name='TblUserChatHistDtl',
            fields=[
                ('CHAT_DTL_ID', models.AutoField(db_column='CHAT_DTL_ID', primary_key=True, serialize=False)),
                ('BOT_YN', models.CharField(db_column='BOT_YN', default='N', max_length=1)),
                ('CHAT_CONTENT', models.CharField(blank=True, db_column='CHAT_CONTENT', max_length=1000, null=True)),
                ('REG_DT', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('CHAT_ID', models.ForeignKey(db_column='CHAT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='chat_details', to='dacare.tbluserchathistory')),
            ],
            options={
                'db_table': 'TBL_USER_CHAT_HIST_DTL',
            },
        ),
        migrations.CreateModel(
            name='TblVerifyCode',
            fields=[
                ('VERIFY_CODE_ID', models.AutoField(db_column='VERIFY_CODE_ID', primary_key=True, serialize=False)),
                ('USER_EMAIL', models.CharField(db_column='USER_EMAIL', max_length=50)),
                ('VERIFY_CODE', models.CharField(db_column='VERIFY_CODE', max_length=50)),
                ('REG_DT', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('REQ_IP', models.CharField(db_column='REQ_IP', max_length=50)),
            ],
            options={
                'db_table': 'TBL_VERIFY_CODE',
                'indexes': [models.Index(fields=['USER_EMAIL'], name='IDX_TBL_VERIFY_CODE_USER_EMAIL')],
            },
        ),
        migrations.CreateModel(
            name='TblFeedback',
            fields=[
                ('FEEDBACK_ID', models.AutoField(db_column='FEEDBACK_ID', primary_key=True, serialize=False)),
                ('SATISFACTION_LEVEL', models.IntegerField(db_column='SATISFACTION_LEVEL', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('FEEDBACK_CONTENT', models.CharField(blank=True, db_column='FEEDBACK_CONTENT', max_length=1000, null=True)),
                ('REG_DT', models.DateTimeField(auto_now_add=True, db_column='REG_DT')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dacare.tbluser')),
            ],
            options={
                'db_table': 'TBL_FEEDBACK',
                'indexes': [models.Index(fields=['USER_ID'], name='IDX_TBL_FEEDBACK_USER_ID')],
                'constraints': [models.CheckConstraint(condition=models.Q(('SATISFACTION_LEVEL__in', [1, 2, 3, 4, 5])), name='CK_TBL_FEEDBACK_SATISFACTION')],
            },
        ),
        migrations.AddIndex(
            model_name='tbluserchathistory',
            index=models.Index(fields=['USER_ID'], name='IDX_CHAT_USER'),
        ),
        migrations.AddIndex(
            model_name='tbluserchathistdtl',
            index=models.Index(fields=['CHAT_ID'], name='IDX_CHAT_DTL'),
        ),
        migrations.AddConstraint(
            model_name='tbluserchathistdtl',
            constraint=models.CheckConstraint(condition=models.Q(('BOT_YN__in', ['Y', 'N'])), name='CK_TBL_CHAT_HIST_DTL_BOT_YN'),
        ),
    ]
